/**
 * Writes src/design-tokens.css from plugin/shared/design-tokens.ts, the single
 * source of truth for spacing, icon, and type roles on both the website and the
 * companion plugin. Run `bun run tokens:build` after editing the module; the
 * output is committed, and scripts/design-tokens.test.ts fails if it drifts.
 */
import { writeFileSync } from "node:fs"
import { join } from "node:path"
import {
  ICON,
  SPACE,
  TYPE,
  type TypeStyle,
} from "../plugin/shared/design-tokens.ts"

const OUTPUT = join(process.cwd(), "src", "design-tokens.css")

const rem = (px: number) => `${px / 16}rem`

function typeUtility(role: string, style: TypeStyle): string {
  const lines = [
    `font-size: ${rem(style.size)};`,
    `line-height: ${rem(style.lineHeight)};`,
    `font-weight: ${style.weight};`,
    `letter-spacing: ${style.tracking}em;`,
  ]
  if (style.uppercase) lines.push("text-transform: uppercase;")
  return `@utility type-${role} {\n${lines.map((l) => `  ${l}`).join("\n")}\n}`
}

export function buildDesignTokensCss(): string {
  const spacing = Object.entries(SPACE).map(
    ([role, px]) => `  --spacing-${role}: ${rem(px)};`
  )
  const icons = Object.entries(ICON).map(
    ([size, px]) => `  --spacing-icon-${size}: ${rem(px)};`
  )
  const types = Object.entries(TYPE).map(([role, style]) =>
    typeUtility(role, style)
  )

  return `/*
 * GENERATED by scripts/build-design-tokens.ts from plugin/shared/design-tokens.ts.
 * Do not edit by hand — change the module and run \`bun run tokens:build\`.
 */

@theme static {
${[...spacing, ...icons].join("\n")}
}

${types.join("\n\n")}
`
}

if (import.meta.main) {
  writeFileSync(OUTPUT, buildDesignTokensCss())
  console.log(`Wrote ${OUTPUT}`)
}
